# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RenommeRue
                                 A QGIS plugin
 plugin de renommage des noms de rues droite et/ou gauche
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-11
        copyright            : (C) 2023 by PECHEUR Gérôme
        email                : gerome.pecheur@ign.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RenommeRue class from file RenommeRue.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .RenommeRue import RenommeRue
    return RenommeRue(iface)
